### ISSUE TITLE
The default HUD is not fit for purpose?

### ISSUE THREAD

**Issue by liback** [nQuake/distfiles#16]
When installing nQuake currently the default HUD is the one in the screenshots below. In my opinion this does not make it fit for purpose (and i guess the gist of the discussion may end up being what nQuake's refined purpose/crowd is or should be) as it makes things too hard to see and players will likely want to make considerably more adaptions compared to then the previous HUD was in place to get a somewhat competitive setup.

I simply suggest to revert the current HUD to the previous one.

**Current HUD**
![ezquake000](https://user-images.githubusercontent.com/15114487/197417974-0155c8d9-6703-4187-aa3a-491752982710.png)
![ezquake001](https://user-images.githubusercontent.com/15114487/197417976-24524c78-fead-40fa-8b8c-8f588779f248.png)

**Previous HUD**
![image](https://user-images.githubusercontent.com/15114487/197417963-1389b68b-b660-45a9-893b-7273a9738020.png)

**Comment by zigg1zagg1** [comment]
Yeah, agreed that the old one is nicer
the reason it was changed was apparently because people wanted something more faithful to the original, tho that one is still far from the vanilla one :/

it also doesnt make sense to keep the simple items but not use those same icons on the hud.

Ive got a WIP updated version of that hud, which shows the correct player colours for the scores, and has things like runes for ctf and itemsclock for spectating:
![ezquake003](https://user-images.githubusercontent.com/73136291/197423341-618843c4-8026-494f-84ed-2f3785d896be.png)
Ive also made matching kill tracker icons to go with it (always bothered me that the nailguns' colours were flipped in the tracker)
![ezquake005](https://user-images.githubusercontent.com/73136291/197423388-224d8eba-9217-452e-88a3-a208702b9937.png)

I'll upload this to gfx.quakeworld.nu at some point, but it would be nice to include it in nquake too.

**Comment by liback** [comment]
I have now done the following:
* Reverted the HUD
* Added Zigg's HUD changes (adapted the score diff element to show minus sign for negatives though and be slightly bigger)
* Added new tracker images

Default HUD now looks as below:
![ezquake000](https://user-images.githubusercontent.com/15114487/198898367-83a9c01c-9b6d-461b-98df-3e13307fd822.png)
